bot_messages:
  greeting: |
    👋🏻 Привет!
    Меня зовут Nudge и моя цель - напоминать тебе о делах и показывать результат твоих действий!
  reg_UTC_request: |
    Введите ваш часовой пояс в формате UTC(введите число со знаком, например +7 или -5):
  reg_UTC_value_error: |
    UTC не допускает значение меньше -12 или больше 14, введите корректное значение
  reg_UTC_format_error: |
    Некорректный формат ввода, попробуйте еще раз
  register: |
    регистрация успешна!
  user_not_found: |
    Пользователь не найден, введите /reg для регистрации
  user_already_exists: |
    Пользователь уже существует
  delete_successfull: |
    Пользователь успешно удален!
  new_task_title_request: |
    Укажите название задачи (ограничение 64 символа):
  new_task_text_request: |
    Укажите текст задачи (ограничение 3000 символов):
  new_task_deadline_request: |
    Укажите срок окончания задачи в формате DD:MM:YYYY:HH:mm или отправьте NONE если задача безсрочная:
  task_withdraw_format: |
    <b>{title}</b>
    {text}

    deadline: {deadline}
