bot_messages:
  greeting: |
    👋🏻 Привет!
    Меня зовут Nudge и моя цель - напоминать тебе о делах и показывать результат твоих действий!
  register: |
    регистрация успешна!
  user_not_found: |
    Извини, ничего не найдено
  delete_successfull: |
    Пользователь успешно удален!
